language: java
jdk:
  - oraclejdk8
script: ./gradlew distZip


# Don't use cache to force the use of the newest jar of the same version
#before_cache:
#  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
#  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
#cache:
#  directories:
#    - $HOME/.gradle/caches/
#    - $HOME/.gradle/wrapper/

deploy:
  - provider: bintray
    file: 'all/build/descriptor/descriptor.json'
    user: $BINTRAY_API_USER
    key: $BINTRAY_API_KEY
    on:
      branch: master
  - provider: bintray
    file: 'simulator/build/descriptor/descriptor.json'
    user: $BINTRAY_API_USER
    key: $BINTRAY_API_KEY
    on:
      branch: master

