plugins {
    id 'base'
}

group = 'org.obpcdl'
version = '2.0.1'

tasks.named('assemble') {
    subprojects.each { dependsOn "${it.name}:assemble" }
}

tasks.named('build') {
    subprojects.each { dependsOn "${it.name}:build" }
}

tasks.named('clean') {
    subprojects.each { dependsOn "${it.name}:clean" }
}

tasks.register('publish') {
    subprojects.each { dependsOn "${it.name}:publish" }
}

subprojects {
    apply plugin: 'distribution'
    apply plugin: 'maven-publish'

    group = 'org.obpcdl'
    version = '2.0.1'

    repositories {
        mavenLocal()
        mavenCentral()
        maven { 
            url = "${OBP2ReadOnlyMavenRepository}"
            allowInsecureProtocol = true 
            metadataSources {
                artifact()
            }
        }
    }

    publishing {
        repositories {
            mavenLocal()
            maven { 
                url = "${OBP2LocalMavenRepository}" 
                allowInsecureProtocol = true
            }
        }
        publications {
            myDistribution(MavenPublication) {
                artifact distZip
            }
        }
    }
}
