plugins {
    id 'application'
    id 'edu.sc.seis.macAppBundle' version '2.3.0'
}

application {
    mainClass = 'obp2.ui2.PlugUI'
    applicationDefaultJvmArgs = [
        '-XX:+ExitOnOutOfMemoryError',
        '-Dapple.laf.useScreenMenuBar=true'
    ]
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(23)
    }
}

distributions {
    main {
        distributionBaseName = project.name
        contents {
            from(project.file('dist')) {
                exclude '*.pyc'
                into '.'
            }
        }
    }
}

macAppBundle {
    mainClassName = 'obp2.ui2.PlugUI'
    icon = 'icon/OBP2.icns'
    javaProperties = [
        'apple.laf.useScreenMenuBar': 'true'
    ]
    dmgName = "${project.name}-osx-${project.version}"
    bundleJRE = false
    jreHome = ''
}

dependencies {
    //UI support
    runtimeOnly 'org.obpcdl:obp2-GUI:2.0.0'
    //LTL support
    runtimeOnly 'org.obpcdl:LTL:2.0.0'
    runtimeOnly 'org.obpcdl:obp2-runtime-buchi:2.0.0'
    runtimeOnly 'org.obpcdl:obp2-runtime-buchikripke:2.0.0'
    //runtimes
    runtimeOnly 'org.obpcdl:obp2-runtime-remote:2.0.0'
}

build.dependsOn createAppZip
